apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
spec:
  project: default
  source:
    repoURL: 'https://github.com/Madisoilihi/lab2.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

